### ISSUE TITLE
installation bug

### ISSUE THREAD

**Issue by karim1871** [razeineldin/Slicer-DeepSeg#1]
Hi

Error i got while installing the DeepSeq module on the last stable slicer version 4.11.20210226 r29738 / 7a593c8:

Python: ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Accès refusé: 'c:\\users\\...\\appdata\\local\\na-mic\\slicer 4.11.20210226\\lib\\python\\lib\\site-packages\\~cipy\\.libs\\libansari.R6EA3HQP5KZ6TAXU4Y4ZVTRPT7UVA53Z.gfortran-win_amd64.dll'

Stream: ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Acc�s refus�: 'c:\\users\\....\\appdata\\local\\na-mic\\slicer 4.11.20210226\\lib\\python\\lib\\site-packages\\~cipy\\.libs\\libansari.R6EA3HQP5KZ6TAXU4Y4ZVTRPT7UVA53Z.gfortran-win_amd64.dll'

Python: Consider using the `--user` option or check the permissions.

Stream: Consider using the `--user` option or check the permissions.

**Comment by razeineldin** [comment]
Hi @karim1871,

This is a permission problem.
Please run the 3D Slicer as an Administrator and it should work. 

Best,
Ramy
