### ISSUE TITLE
output volume has only zero scalar values

### ISSUE THREAD

**Issue by matthieufaillot** [razeineldin/Slicer-DeepSeg#2]
Hi,
I am running  SlicerDeepSeg on macOs 10.14.16 Slicer 4.11.20210226 
**problem :** when input is a clinical anisotropic non 3D flair volume :  the output  is a volume of the same size and pixdim as input image but the scalar values are ony zero
I reproduced the issue with many files and  on more recent macOS and slicer versions
Thanks
Matthieu
> Pre-processing
Loadind data completed in 0.01 seconds
Pre-processing data completed in 0.13 seconds
Getting DeepSeg Model
A local file was found, but it seems to be incomplete or outdated because the sha256 file hash does not match the original value of 941eb4b2c7da98310a95176e7adabe8f84d2e3df so we will re-download the data.
Downloading data from https://github.com/razeineldin/Test_Data/raw/main/model_DeepSeg_21.h5

    8192/10531824 [..............................] - ETA: 19s
   40960/10531824 [..............................] - ETA: 23s
   65536/10531824 [..............................] - ETA: 26s
   81920/10531824 [..............................] - ETA: 32s
   98304/10531824 [..............................] - ETA: 34s
  131072/10531824 [..............................] - ETA: 30s
  147456/10531824 [..............................] - ETA: 2:10
  311296/10531824 [..............................] - ETA: 1:09
  327680/10531824 [..............................] - ETA: 1:08
  344064/10531824 [..............................] - ETA: 1:08
  360448/10531824 [>.............................] - ETA: 1:08
  393216/10531824 [>.............................] - ETA: 1:21
  409600/10531824 [>.............................] - ETA: 1:21
  425984/10531824 [>.............................] - ETA: 1:19
  442368/10531824 [>.............................] - ETA: 1:20
  475136/10531824 [>.............................] - ETA: 1:20
  491520/10531824 [>.............................] - ETA: 1:20
  524288/10531824 [>.............................] - ETA: 1:17
  540672/10531824 [>.............................] - ETA: 1:17
  573440/10531824 [>.............................] - ETA: 1:14
  622592/10531824 [>.............................] - ETA: 1:09
  655360/10531824 [>.............................] - ETA: 1:06
  671744/10531824 [>.............................] - ETA: 1:05
  720896/10531824 [=>............................] - ETA: 1:02
  737280/10531824 [=>............................] - ETA: 1:04
  770048/10531824 [=>............................] - ETA: 1:03
  802816/10531824 [=>............................] - ETA: 1:01
  851968/10531824 [=>............................] - ETA: 59s 
  901120/10531824 [=>............................] - ETA: 56s
  933888/10531824 [=>............................] - ETA: 55s
  950272/10531824 [=>............................] - ETA: 55s
 1015808/10531824 [=>............................] - ETA: 51s
 1064960/10531824 [==>...........................] - ETA: 49s
 1097728/10531824 [==>...........................] - ETA: 53s
 1310720/10531824 [==>...........................] - ETA: 44s
 1327104/10531824 [==>...........................] - ETA: 44s
 1392640/10531824 [==>...........................] - ETA: 42s
 1425408/10531824 [===>..........................] - ETA: 42s
 1441792/10531824 [===>..........................] - ETA: 42s
 1474560/10531824 [===>..........................] - ETA: 42s
 1540096/10531824 [===>..........................] - ETA: 41s
 1581056/10531824 [===>..........................] - ETA: 40s
 1589248/10531824 [===>..........................] - ETA: 40s
 1622016/10531824 [===>..........................] - ETA: 40s
 1638400/10531824 [===>..........................] - ETA: 40s
 1687552/10531824 [===>..........................] - ETA: 39s
 1703936/10531824 [===>..........................] - ETA: 39s
 1753088/10531824 [===>..........................] - ETA: 38s
 1769472/10531824 [====>.........................] - ETA: 38s
 1785856/10531824 [====>.........................] - ETA: 39s
 1802240/10531824 [====>.........................] - ETA: 39s
 1851392/10531824 [====>.........................] - ETA: 38s
 1867776/10531824 [====>.........................] - ETA: 38s
 1884160/10531824 [====>.........................] - ETA: 38s
 1900544/10531824 [====>.........................] - ETA: 38s
 1933312/10531824 [====>.........................] - ETA: 38s
 1949696/10531824 [====>.........................] - ETA: 37s
 1966080/10531824 [====>.........................] - ETA: 37s
 1998848/10531824 [====>.........................] - ETA: 39s
 2031616/10531824 [====>.........................] - ETA: 38s
 2064384/10531824 [====>.........................] - ETA: 38s
 2097152/10531824 [====>.........................] - ETA: 37s
 2113536/10531824 [=====>........................] - ETA: 37s
 2179072/10531824 [=====>........................] - ETA: 36s
 2195456/10531824 [=====>........................] - ETA: 36s
 2228224/10531824 [=====>........................] - ETA: 39s
 2424832/10531824 [=====>........................] - ETA: 36s
 2441216/10531824 [=====>........................] - ETA: 35s
 2457600/10531824 [======>.......................] - ETA: 36s
 2473984/10531824 [======>.......................] - ETA: 36s
 2490368/10531824 [======>.......................] - ETA: 36s
 2523136/10531824 [======>.......................] - ETA: 36s
 2572288/10531824 [======>.......................] - ETA: 36s
 2605056/10531824 [======>.......................] - ETA: 35s
 2621440/10531824 [======>.......................] - ETA: 35s
 2654208/10531824 [======>.......................] - ETA: 35s
 2670592/10531824 [======>.......................] - ETA: 35s
 2686976/10531824 [======>.......................] - ETA: 35s
 2719744/10531824 [======>.......................] - ETA: 35s
 2768896/10531824 [======>.......................] - ETA: 34s
 2818048/10531824 [=======>......................] - ETA: 34s
 2850816/10531824 [=======>......................] - ETA: 34s
 2883584/10531824 [=======>......................] - ETA: 33s
 2899968/10531824 [=======>......................] - ETA: 33s
 2965504/10531824 [=======>......................] - ETA: 32s
 3014656/10531824 [=======>......................] - ETA: 32s
 3047424/10531824 [=======>......................] - ETA: 32s
 3096576/10531824 [=======>......................] - ETA: 31s
 3145728/10531824 [=======>......................] - ETA: 31s
 3194880/10531824 [========>.....................] - ETA: 30s
 3211264/10531824 [========>.....................] - ETA: 31s
 3244032/10531824 [========>.....................] - ETA: 30s
 3276800/10531824 [========>.....................] - ETA: 30s
 3293184/10531824 [========>.....................] - ETA: 30s
 3325952/10531824 [========>.....................] - ETA: 30s
 3358720/10531824 [========>.....................] - ETA: 29s
 3391488/10531824 [========>.....................] - ETA: 30s
 3440640/10531824 [========>.....................] - ETA: 29s
 3473408/10531824 [========>.....................] - ETA: 29s
 3522560/10531824 [=========>....................] - ETA: 28s
 3555328/10531824 [=========>....................] - ETA: 28s
 3571712/10531824 [=========>....................] - ETA: 28s
 3588096/10531824 [=========>....................] - ETA: 28s
 3637248/10531824 [=========>....................] - ETA: 28s
 3670016/10531824 [=========>....................] - ETA: 27s
 3702784/10531824 [=========>....................] - ETA: 28s
 3735552/10531824 [=========>....................] - ETA: 27s
 3801088/10531824 [=========>....................] - ETA: 27s
 3833856/10531824 [=========>....................] - ETA: 27s
 3850240/10531824 [=========>....................] - ETA: 27s
 3899392/10531824 [==========>...................] - ETA: 26s
 3964928/10531824 [==========>...................] - ETA: 26s
 4046848/10531824 [==========>...................] - ETA: 25s
 4079616/10531824 [==========>...................] - ETA: 25s
 4194304/10531824 [==========>...................] - ETA: 24s
 4259840/10531824 [===========>..................] - ETA: 23s
 4390912/10531824 [===========>..................] - ETA: 23s
 4587520/10531824 [============>.................] - ETA: 21s
 4603904/10531824 [============>.................] - ETA: 21s
 4636672/10531824 [============>.................] - ETA: 21s
 4669440/10531824 [============>.................] - ETA: 21s
 4718592/10531824 [============>.................] - ETA: 20s
 4751360/10531824 [============>.................] - ETA: 20s
 4767744/10531824 [============>.................] - ETA: 20s
 4800512/10531824 [============>.................] - ETA: 20s
 4849664/10531824 [============>.................] - ETA: 20s
 4882432/10531824 [============>.................] - ETA: 20s
 4931584/10531824 [=============>................] - ETA: 20s
 4947968/10531824 [=============>................] - ETA: 20s
 4980736/10531824 [=============>................] - ETA: 20s
 5029888/10531824 [=============>................] - ETA: 19s
 5079040/10531824 [=============>................] - ETA: 19s
 5128192/10531824 [=============>................] - ETA: 19s
 5160960/10531824 [=============>................] - ETA: 19s
 5177344/10531824 [=============>................] - ETA: 19s
 5308416/10531824 [==============>...............] - ETA: 18s
 5341184/10531824 [==============>...............] - ETA: 18s
 5373952/10531824 [==============>...............] - ETA: 18s
 5390336/10531824 [==============>...............] - ETA: 18s
 5455872/10531824 [==============>...............] - ETA: 17s
 5505024/10531824 [==============>...............] - ETA: 17s
 5537792/10531824 [==============>...............] - ETA: 17s
 5586944/10531824 [==============>...............] - ETA: 17s
 5603328/10531824 [==============>...............] - ETA: 17s
 5652480/10531824 [===============>..............] - ETA: 17s
 5718016/10531824 [===============>..............] - ETA: 16s
 5783552/10531824 [===============>..............] - ETA: 16s
 5832704/10531824 [===============>..............] - ETA: 16s
 5849088/10531824 [===============>..............] - ETA: 16s
 5947392/10531824 [===============>..............] - ETA: 15s
 5980160/10531824 [================>.............] - ETA: 15s
 6029312/10531824 [================>.............] - ETA: 15s
 6094848/10531824 [================>.............] - ETA: 15s
 6144000/10531824 [================>.............] - ETA: 14s
 6242304/10531824 [================>.............] - ETA: 14s
 6275072/10531824 [================>.............] - ETA: 14s
 6291456/10531824 [================>.............] - ETA: 14s
 6324224/10531824 [=================>............] - ETA: 14s
 6406144/10531824 [=================>............] - ETA: 13s
 6455296/10531824 [=================>............] - ETA: 13s
 6569984/10531824 [=================>............] - ETA: 13s
 6586368/10531824 [=================>............] - ETA: 13s
 6619136/10531824 [=================>............] - ETA: 13s
 6684672/10531824 [==================>...........] - ETA: 12s
 6717440/10531824 [==================>...........] - ETA: 12s
 6733824/10531824 [==================>...........] - ETA: 12s
 6832128/10531824 [==================>...........] - ETA: 12s
 6864896/10531824 [==================>...........] - ETA: 12s
 6897664/10531824 [==================>...........] - ETA: 12s
 6963200/10531824 [==================>...........] - ETA: 11s
 6995968/10531824 [==================>...........] - ETA: 11s
 7045120/10531824 [===================>..........] - ETA: 11s
 7094272/10531824 [===================>..........] - ETA: 11s
 7143424/10531824 [===================>..........] - ETA: 11s
 7208960/10531824 [===================>..........] - ETA: 11s
 7258112/10531824 [===================>..........] - ETA: 10s
 7290880/10531824 [===================>..........] - ETA: 10s
 7323648/10531824 [===================>..........] - ETA: 10s
 7372800/10531824 [====================>.........] - ETA: 10s
 7389184/10531824 [====================>.........] - ETA: 10s
 7421952/10531824 [====================>.........] - ETA: 10s
 7438336/10531824 [====================>.........] - ETA: 10s
 7487488/10531824 [====================>.........] - ETA: 10s
 7520256/10531824 [====================>.........] - ETA: 9s 
 7569408/10531824 [====================>.........] - ETA: 9s
 7618560/10531824 [====================>.........] - ETA: 9s
 7651328/10531824 [====================>.........] - ETA: 9s
 7667712/10531824 [====================>.........] - ETA: 9s
 7684096/10531824 [====================>.........] - ETA: 9s
 7700480/10531824 [====================>.........] - ETA: 9s
 7716864/10531824 [====================>.........] - ETA: 9s
 7749632/10531824 [=====================>........] - ETA: 9s
 7782400/10531824 [=====================>........] - ETA: 9s
 7815168/10531824 [=====================>........] - ETA: 9s
 7864320/10531824 [=====================>........] - ETA: 8s
 7880704/10531824 [=====================>........] - ETA: 8s
 7929856/10531824 [=====================>........] - ETA: 8s
 7979008/10531824 [=====================>........] - ETA: 8s
 7995392/10531824 [=====================>........] - ETA: 8s
 8044544/10531824 [=====================>........] - ETA: 8s
 8077312/10531824 [======================>.......] - ETA: 8s
 8093696/10531824 [======================>.......] - ETA: 8s
 8142848/10531824 [======================>.......] - ETA: 8s
 8175616/10531824 [======================>.......] - ETA: 7s
 8192000/10531824 [======================>.......] - ETA: 7s
 8208384/10531824 [======================>.......] - ETA: 7s
 8224768/10531824 [======================>.......] - ETA: 7s
 8257536/10531824 [======================>.......] - ETA: 7s
 8306688/10531824 [======================>.......] - ETA: 7s
 8323072/10531824 [======================>.......] - ETA: 7s
 8339456/10531824 [======================>.......] - ETA: 7s
 8388608/10531824 [======================>.......] - ETA: 7s
 8437760/10531824 [=======================>......] - ETA: 7s
 8454144/10531824 [=======================>......] - ETA: 7s
 8486912/10531824 [=======================>......] - ETA: 6s
 8519680/10531824 [=======================>......] - ETA: 6s
 8601600/10531824 [=======================>......] - ETA: 6s
 8634368/10531824 [=======================>......] - ETA: 6s
 8667136/10531824 [=======================>......] - ETA: 6s
 8683520/10531824 [=======================>......] - ETA: 6s
 8732672/10531824 [=======================>......] - ETA: 6s
 8798208/10531824 [========================>.....] - ETA: 6s
 8830976/10531824 [========================>.....] - ETA: 5s
 8847360/10531824 [========================>.....] - ETA: 5s
 8880128/10531824 [========================>.....] - ETA: 5s
 8896512/10531824 [========================>.....] - ETA: 5s
 8912896/10531824 [========================>.....] - ETA: 5s
 8945664/10531824 [========================>.....] - ETA: 5s
 8962048/10531824 [========================>.....] - ETA: 5s
 8978432/10531824 [========================>.....] - ETA: 5s
 8994816/10531824 [========================>.....] - ETA: 5s
 9027584/10531824 [========================>.....] - ETA: 5s
 9043968/10531824 [========================>.....] - ETA: 5s
 9076736/10531824 [========================>.....] - ETA: 5s
 9093120/10531824 [========================>.....] - ETA: 5s
 9125888/10531824 [========================>.....] - ETA: 5s
 9142272/10531824 [=========================>....] - ETA: 5s
 9175040/10531824 [=========================>....] - ETA: 5s
 9207808/10531824 [=========================>....] - ETA: 4s
 9240576/10531824 [=========================>....] - ETA: 4s
 9256960/10531824 [=========================>....] - ETA: 4s
 9273344/10531824 [=========================>....] - ETA: 4s
 9289728/10531824 [=========================>....] - ETA: 4s
 9306112/10531824 [=========================>....] - ETA: 4s
 9338880/10531824 [=========================>....] - ETA: 4s
 9371648/10531824 [=========================>....] - ETA: 4s
 9404416/10531824 [=========================>....] - ETA: 4s
 9420800/10531824 [=========================>....] - ETA: 4s
 9437184/10531824 [=========================>....] - ETA: 4s
 9469952/10531824 [=========================>....] - ETA: 4s
 9486336/10531824 [==========================>...] - ETA: 3s
 9519104/10531824 [==========================>...] - ETA: 3s
 9535488/10531824 [==========================>...] - ETA: 3s
 9568256/10531824 [==========================>...] - ETA: 3s
 9617408/10531824 [==========================>...] - ETA: 3s
 9633792/10531824 [==========================>...] - ETA: 3s
 9666560/10531824 [==========================>...] - ETA: 3s
 9699328/10531824 [==========================>...] - ETA: 3s
 9715712/10531824 [==========================>...] - ETA: 3s
 9732096/10531824 [==========================>...] - ETA: 3s
 9797632/10531824 [==========================>...] - ETA: 2s
 9830400/10531824 [===========================>..] - ETA: 2s
 9895936/10531824 [===========================>..] - ETA: 2s
 9912320/10531824 [===========================>..] - ETA: 2s
10010624/10531824 [===========================>..] - ETA: 1s
10043392/10531824 [===========================>..] - ETA: 1s
10092544/10531824 [===========================>..] - ETA: 1s
10190848/10531824 [============================>.] - ETA: 1s
10240000/10531824 [============================>.] - ETA: 1s
10305536/10531824 [============================>.] - ETA: 0s
10420224/10531824 [============================>.] - ETA: 0s
10485760/10531824 [============================>.] - ETA: 0s
10534912/10531824 [==============================] - 39s 4us/step
Getting pre-trained model completed in 41.32 seconds
Prediction completed in 12.97 seconds
Showing 3D View
Visualization completed in 1.02 seconds

**Comment by razeineldin** [comment]
Hello @matthieufaillot,

Thanks for your interest in our work and I am sorry for my late reply.

Please refer to [my reply to your other issue "_Failed to compute results_"](https://github.com/razeineldin/Slicer-DeepSeg/issues/3#issuecomment-1217999507)

Best,
Ramy
