### ISSUE TITLE
Failed to compute results : could not broadcast because of shape

### ISSUE THREAD

**Issue by matthieufaillot** [razeineldin/Slicer-DeepSeg#3]
Hi,
I am running SlicerDeepSeg on macOs 10.14.16 Slicer 4.11.20210226
**problem :** when processing clinical anisotropic 3D resolution files,  SlicerDeepSeg stops at 40% and outputs the following message : Failed to compute results: could not broadcast input array from shape (192,224,158) into shape (192,224,160)
I reproduced the issue with many files and on more recent macOS and slicer versions
Thanks
Matthieu

`re-processing
Loadind data completed in 0.00 seconds
Pre-processing data completed in 0.27 seconds
Getting DeepSeg Model
A local file was found, but it seems to be incomplete or outdated because the sha256 file hash does not match the original value of 941eb4b2c7da98310a95176e7adabe8f84d2e3df so we will re-download the data.
Downloading data from https://github.com/razeineldin/Test_Data/raw/main/model_DeepSeg_21.h5

    8192/10531824 [..............................] - ETA: 1:46
   16384/10531824 [..............................] - ETA: 2:13
   40960/10531824 [..............................] - ETA: 1:31
   65536/10531824 [..............................] - ETA: 3:39
  131072/10531824 [..............................] - ETA: 2:08
  147456/10531824 [..............................] - ETA: 2:15
  180224/10531824 [..............................] - ETA: 1:55
  196608/10531824 [..............................] - ETA: 1:52
  229376/10531824 [..............................] - ETA: 1:43
  253952/10531824 [..............................] - ETA: 1:35
  278528/10531824 [..............................] - ETA: 1:31
  311296/10531824 [..............................] - ETA: 1:23
  344064/10531824 [..............................] - ETA: 1:17
  360448/10531824 [>.............................] - ETA: 1:15
  393216/10531824 [>.............................] - ETA: 1:18
  409600/10531824 [>.............................] - ETA: 1:17
  425984/10531824 [>.............................] - ETA: 1:19
  458752/10531824 [>.............................] - ETA: 1:16
  475136/10531824 [>.............................] - ETA: 1:25
  524288/10531824 [>.............................] - ETA: 1:20
  589824/10531824 [>.............................] - ETA: 1:15
  606208/10531824 [>.............................] - ETA: 1:14
  622592/10531824 [>.............................] - ETA: 1:15
  655360/10531824 [>.............................] - ETA: 1:18
  671744/10531824 [>.............................] - ETA: 1:17
  688128/10531824 [>.............................] - ETA: 1:17
  704512/10531824 [=>............................] - ETA: 1:17
  737280/10531824 [=>............................] - ETA: 1:15
  753664/10531824 [=>............................] - ETA: 1:15
  770048/10531824 [=>............................] - ETA: 1:19
  835584/10531824 [=>............................] - ETA: 1:15
  868352/10531824 [=>............................] - ETA: 1:13
  901120/10531824 [=>............................] - ETA: 1:11
  917504/10531824 [=>............................] - ETA: 1:10
  950272/10531824 [=>............................] - ETA: 1:08
  983040/10531824 [=>............................] - ETA: 1:06
 1015808/10531824 [=>............................] - ETA: 1:06
 1048576/10531824 [=>............................] - ETA: 1:05
 1097728/10531824 [==>...........................] - ETA: 1:02
 1114112/10531824 [==>...........................] - ETA: 1:02
 1130496/10531824 [==>...........................] - ETA: 1:02
 1146880/10531824 [==>...........................] - ETA: 1:02
 1212416/10531824 [==>...........................] - ETA: 59s 
 1245184/10531824 [==>...........................] - ETA: 58s
 1261568/10531824 [==>...........................] - ETA: 57s
 1294336/10531824 [==>...........................] - ETA: 56s
 1310720/10531824 [==>...........................] - ETA: 57s
 1343488/10531824 [==>...........................] - ETA: 56s
 1359872/10531824 [==>...........................] - ETA: 56s
 1376256/10531824 [==>...........................] - ETA: 56s
 1392640/10531824 [==>...........................] - ETA: 56s
 1409024/10531824 [===>..........................] - ETA: 56s
 1458176/10531824 [===>..........................] - ETA: 54s
 1490944/10531824 [===>..........................] - ETA: 54s
 1507328/10531824 [===>..........................] - ETA: 56s
 1572864/10531824 [===>..........................] - ETA: 54s
 1605632/10531824 [===>..........................] - ETA: 54s
 1622016/10531824 [===>..........................] - ETA: 53s
 1638400/10531824 [===>..........................] - ETA: 54s
 1654784/10531824 [===>..........................] - ETA: 53s
 1671168/10531824 [===>..........................] - ETA: 54s
 1687552/10531824 [===>..........................] - ETA: 54s
 1703936/10531824 [===>..........................] - ETA: 56s
 1736704/10531824 [===>..........................] - ETA: 56s
 1753088/10531824 [===>..........................] - ETA: 57s
 1785856/10531824 [====>.........................] - ETA: 58s
 1818624/10531824 [====>.........................] - ETA: 59s
 1835008/10531824 [====>.........................] - ETA: 1:01
 1851392/10531824 [====>.........................] - ETA: 1:01
 1867776/10531824 [====>.........................] - ETA: 1:02
 1884160/10531824 [====>.........................] - ETA: 1:03
 1900544/10531824 [====>.........................] - ETA: 1:03
 1916928/10531824 [====>.........................] - ETA: 1:03
 1933312/10531824 [====>.........................] - ETA: 1:05
 1949696/10531824 [====>.........................] - ETA: 1:06
 1966080/10531824 [====>.........................] - ETA: 1:06
 1982464/10531824 [====>.........................] - ETA: 1:05
 1998848/10531824 [====>.........................] - ETA: 1:08
 2015232/10531824 [====>.........................] - ETA: 1:11
 2031616/10531824 [====>.........................] - ETA: 1:11
 2048000/10531824 [====>.........................] - ETA: 1:13
 2064384/10531824 [====>.........................] - ETA: 1:13
 2080768/10531824 [====>.........................] - ETA: 1:13
 2097152/10531824 [====>.........................] - ETA: 1:15
 2113536/10531824 [=====>........................] - ETA: 1:14
 2129920/10531824 [=====>........................] - ETA: 1:14
 2162688/10531824 [=====>........................] - ETA: 1:14
 2179072/10531824 [=====>........................] - ETA: 1:13
 2195456/10531824 [=====>........................] - ETA: 1:13
 2211840/10531824 [=====>........................] - ETA: 1:14
 2244608/10531824 [=====>........................] - ETA: 1:13
 2260992/10531824 [=====>........................] - ETA: 1:12
 2277376/10531824 [=====>........................] - ETA: 1:12
 2293760/10531824 [=====>........................] - ETA: 1:12
 2310144/10531824 [=====>........................] - ETA: 1:12
 2342912/10531824 [=====>........................] - ETA: 1:11
 2359296/10531824 [=====>........................] - ETA: 1:12
 2375680/10531824 [=====>........................] - ETA: 1:11
 2392064/10531824 [=====>........................] - ETA: 1:11
 2408448/10531824 [=====>........................] - ETA: 1:11
 2424832/10531824 [=====>........................] - ETA: 1:11
 2441216/10531824 [=====>........................] - ETA: 1:10
 2457600/10531824 [======>.......................] - ETA: 1:10
 2473984/10531824 [======>.......................] - ETA: 1:10
 2490368/10531824 [======>.......................] - ETA: 1:09
 2506752/10531824 [======>.......................] - ETA: 1:13
 2621440/10531824 [======>.......................] - ETA: 1:10
 2637824/10531824 [======>.......................] - ETA: 1:10
 2654208/10531824 [======>.......................] - ETA: 1:12
 2736128/10531824 [======>.......................] - ETA: 1:10
 2752512/10531824 [======>.......................] - ETA: 1:10
 2768896/10531824 [======>.......................] - ETA: 1:10
 2818048/10531824 [=======>......................] - ETA: 1:09
 2834432/10531824 [=======>......................] - ETA: 1:09
 2883584/10531824 [=======>......................] - ETA: 1:08
 2899968/10531824 [=======>......................] - ETA: 1:08
 2916352/10531824 [=======>......................] - ETA: 1:08
 2932736/10531824 [=======>......................] - ETA: 1:08
 2949120/10531824 [=======>......................] - ETA: 1:08
 2981888/10531824 [=======>......................] - ETA: 1:07
 3014656/10531824 [=======>......................] - ETA: 1:06
 3031040/10531824 [=======>......................] - ETA: 1:06
 3047424/10531824 [=======>......................] - ETA: 1:06
 3063808/10531824 [=======>......................] - ETA: 1:07
 3112960/10531824 [=======>......................] - ETA: 1:06
 3129344/10531824 [=======>......................] - ETA: 1:06
 3145728/10531824 [=======>......................] - ETA: 1:06
 3178496/10531824 [========>.....................] - ETA: 1:06
 3194880/10531824 [========>.....................] - ETA: 1:06
 3211264/10531824 [========>.....................] - ETA: 1:06
 3227648/10531824 [========>.....................] - ETA: 1:06
 3244032/10531824 [========>.....................] - ETA: 1:06
 3260416/10531824 [========>.....................] - ETA: 1:06
 3276800/10531824 [========>.....................] - ETA: 1:05
 3293184/10531824 [========>.....................] - ETA: 1:05
 3309568/10531824 [========>.....................] - ETA: 1:05
 3325952/10531824 [========>.....................] - ETA: 1:05
 3342336/10531824 [========>.....................] - ETA: 1:05
 3358720/10531824 [========>.....................] - ETA: 1:05
 3375104/10531824 [========>.....................] - ETA: 1:05
 3391488/10531824 [========>.....................] - ETA: 1:05
 3407872/10531824 [========>.....................] - ETA: 1:05
 3424256/10531824 [========>.....................] - ETA: 1:05
 3440640/10531824 [========>.....................] - ETA: 1:05
 3457024/10531824 [========>.....................] - ETA: 1:05
 3473408/10531824 [========>.....................] - ETA: 1:04
 3506176/10531824 [========>.....................] - ETA: 1:04
 3522560/10531824 [=========>....................] - ETA: 1:04
 3538944/10531824 [=========>....................] - ETA: 1:04
 3555328/10531824 [=========>....................] - ETA: 1:03
 3571712/10531824 [=========>....................] - ETA: 1:04
 3588096/10531824 [=========>....................] - ETA: 1:04
 3604480/10531824 [=========>....................] - ETA: 1:04
 3637248/10531824 [=========>....................] - ETA: 1:03
 3653632/10531824 [=========>....................] - ETA: 1:03
 3686400/10531824 [=========>....................] - ETA: 1:03
 3702784/10531824 [=========>....................] - ETA: 1:02
 3719168/10531824 [=========>....................] - ETA: 1:02
 3735552/10531824 [=========>....................] - ETA: 1:02
 3768320/10531824 [=========>....................] - ETA: 1:02
 3784704/10531824 [=========>....................] - ETA: 1:01
 3801088/10531824 [=========>....................] - ETA: 1:01
 3817472/10531824 [=========>....................] - ETA: 1:01
 3833856/10531824 [=========>....................] - ETA: 1:01
 3850240/10531824 [=========>....................] - ETA: 1:01
 3866624/10531824 [==========>...................] - ETA: 1:01
 3883008/10531824 [==========>...................] - ETA: 1:01
 3899392/10531824 [==========>...................] - ETA: 1:01
 3915776/10531824 [==========>...................] - ETA: 1:00
 3932160/10531824 [==========>...................] - ETA: 1:00
 3948544/10531824 [==========>...................] - ETA: 1:01
 3964928/10531824 [==========>...................] - ETA: 1:01
 3981312/10531824 [==========>...................] - ETA: 1:01
 3997696/10531824 [==========>...................] - ETA: 1:00
 4014080/10531824 [==========>...................] - ETA: 1:01
 4030464/10531824 [==========>...................] - ETA: 1:01
 4046848/10531824 [==========>...................] - ETA: 1:01
 4079616/10531824 [==========>...................] - ETA: 1:00
 4096000/10531824 [==========>...................] - ETA: 1:00
 4112384/10531824 [==========>...................] - ETA: 1:04
 4243456/10531824 [===========>..................] - ETA: 1:03
 4341760/10531824 [===========>..................] - ETA: 1:02
 4374528/10531824 [===========>..................] - ETA: 1:01
 4390912/10531824 [===========>..................] - ETA: 1:01
 4423680/10531824 [===========>..................] - ETA: 1:02
 4440064/10531824 [===========>..................] - ETA: 1:01
 4505600/10531824 [===========>..................] - ETA: 1:01
 4554752/10531824 [===========>..................] - ETA: 1:00
 4571136/10531824 [============>.................] - ETA: 1:00
 4603904/10531824 [============>.................] - ETA: 1:00
 4620288/10531824 [============>.................] - ETA: 1:00
 4669440/10531824 [============>.................] - ETA: 59s 
 4685824/10531824 [============>.................] - ETA: 59s
 4702208/10531824 [============>.................] - ETA: 59s
 4718592/10531824 [============>.................] - ETA: 58s
 4734976/10531824 [============>.................] - ETA: 58s
 4767744/10531824 [============>.................] - ETA: 58s
 4784128/10531824 [============>.................] - ETA: 58s
 4816896/10531824 [============>.................] - ETA: 57s
 4833280/10531824 [============>.................] - ETA: 58s
 4866048/10531824 [============>.................] - ETA: 57s
 4882432/10531824 [============>.................] - ETA: 57s
 4898816/10531824 [============>.................] - ETA: 57s
 4915200/10531824 [=============>................] - ETA: 57s
 4931584/10531824 [=============>................] - ETA: 57s
 4964352/10531824 [=============>................] - ETA: 56s
 4980736/10531824 [=============>................] - ETA: 56s
 4997120/10531824 [=============>................] - ETA: 56s
 5013504/10531824 [=============>................] - ETA: 55s
 5029888/10531824 [=============>................] - ETA: 55s
 5046272/10531824 [=============>................] - ETA: 55s
 5062656/10531824 [=============>................] - ETA: 54s
 5095424/10531824 [=============>................] - ETA: 54s
 5111808/10531824 [=============>................] - ETA: 54s
 5128192/10531824 [=============>................] - ETA: 54s
 5144576/10531824 [=============>................] - ETA: 54s
 5160960/10531824 [=============>................] - ETA: 54s
 5177344/10531824 [=============>................] - ETA: 54s
 5193728/10531824 [=============>................] - ETA: 55s
 5210112/10531824 [=============>................] - ETA: 55s
 5226496/10531824 [=============>................] - ETA: 55s
 5242880/10531824 [=============>................] - ETA: 55s
 5259264/10531824 [=============>................] - ETA: 55s
 5275648/10531824 [==============>...............] - ETA: 55s
 5292032/10531824 [==============>...............] - ETA: 56s
 5308416/10531824 [==============>...............] - ETA: 55s
 5324800/10531824 [==============>...............] - ETA: 55s
 5341184/10531824 [==============>...............] - ETA: 56s
 5373952/10531824 [==============>...............] - ETA: 55s
 5390336/10531824 [==============>...............] - ETA: 55s
 5406720/10531824 [==============>...............] - ETA: 55s
 5423104/10531824 [==============>...............] - ETA: 55s
 5455872/10531824 [==============>...............] - ETA: 54s
 5488640/10531824 [==============>...............] - ETA: 54s
 5521408/10531824 [==============>...............] - ETA: 53s
 5537792/10531824 [==============>...............] - ETA: 53s
 5554176/10531824 [==============>...............] - ETA: 53s
 5570560/10531824 [==============>...............] - ETA: 53s
 5586944/10531824 [==============>...............] - ETA: 53s
 5603328/10531824 [==============>...............] - ETA: 52s
 5619712/10531824 [===============>..............] - ETA: 52s
 5652480/10531824 [===============>..............] - ETA: 52s
 5668864/10531824 [===============>..............] - ETA: 51s
 5685248/10531824 [===============>..............] - ETA: 51s
 5718016/10531824 [===============>..............] - ETA: 51s
 5734400/10531824 [===============>..............] - ETA: 50s
 5750784/10531824 [===============>..............] - ETA: 50s
 5767168/10531824 [===============>..............] - ETA: 50s
 5799936/10531824 [===============>..............] - ETA: 49s
 5832704/10531824 [===============>..............] - ETA: 49s
 5865472/10531824 [===============>..............] - ETA: 48s
 5881856/10531824 [===============>..............] - ETA: 48s
 5898240/10531824 [===============>..............] - ETA: 48s
 5931008/10531824 [===============>..............] - ETA: 47s
 5947392/10531824 [===============>..............] - ETA: 47s
 5980160/10531824 [================>.............] - ETA: 47s
 6029312/10531824 [================>.............] - ETA: 46s
 6045696/10531824 [================>.............] - ETA: 46s
 6078464/10531824 [================>.............] - ETA: 45s
 6094848/10531824 [================>.............] - ETA: 45s
 6144000/10531824 [================>.............] - ETA: 44s
 6160384/10531824 [================>.............] - ETA: 44s
 6176768/10531824 [================>.............] - ETA: 44s
 6193152/10531824 [================>.............] - ETA: 44s
 6209536/10531824 [================>.............] - ETA: 44s
 6275072/10531824 [================>.............] - ETA: 43s
 6291456/10531824 [================>.............] - ETA: 43s
 6307840/10531824 [================>.............] - ETA: 42s
 6324224/10531824 [=================>............] - ETA: 42s
 6340608/10531824 [=================>............] - ETA: 43s
 6569984/10531824 [=================>............] - ETA: 40s
 6586368/10531824 [=================>............] - ETA: 39s
 6602752/10531824 [=================>............] - ETA: 39s
 6619136/10531824 [=================>............] - ETA: 39s
 6799360/10531824 [==================>...........] - ETA: 37s
 6815744/10531824 [==================>...........] - ETA: 36s
 6832128/10531824 [==================>...........] - ETA: 36s
 6848512/10531824 [==================>...........] - ETA: 36s
 6864896/10531824 [==================>...........] - ETA: 36s
 6881280/10531824 [==================>...........] - ETA: 36s
 6897664/10531824 [==================>...........] - ETA: 36s
 6914048/10531824 [==================>...........] - ETA: 35s
 6930432/10531824 [==================>...........] - ETA: 35s
 6963200/10531824 [==================>...........] - ETA: 35s
 6995968/10531824 [==================>...........] - ETA: 34s
 7012352/10531824 [==================>...........] - ETA: 34s
 7045120/10531824 [===================>..........] - ETA: 34s
 7061504/10531824 [===================>..........] - ETA: 34s
 7077888/10531824 [===================>..........] - ETA: 33s
 7110656/10531824 [===================>..........] - ETA: 33s
 7143424/10531824 [===================>..........] - ETA: 33s
 7159808/10531824 [===================>..........] - ETA: 33s
 7192576/10531824 [===================>..........] - ETA: 32s
 7208960/10531824 [===================>..........] - ETA: 32s
 7258112/10531824 [===================>..........] - ETA: 31s
 7274496/10531824 [===================>..........] - ETA: 31s
 7290880/10531824 [===================>..........] - ETA: 31s
 7307264/10531824 [===================>..........] - ETA: 31s
 7323648/10531824 [===================>..........] - ETA: 31s
 7471104/10531824 [====================>.........] - ETA: 29s
 7503872/10531824 [====================>.........] - ETA: 29s
 7520256/10531824 [====================>.........] - ETA: 29s
 7536640/10531824 [====================>.........] - ETA: 28s
 7585792/10531824 [====================>.........] - ETA: 28s
 7618560/10531824 [====================>.........] - ETA: 28s
 7651328/10531824 [====================>.........] - ETA: 27s
 7684096/10531824 [====================>.........] - ETA: 27s
 7716864/10531824 [====================>.........] - ETA: 26s
 7749632/10531824 [=====================>........] - ETA: 26s
 7766016/10531824 [=====================>........] - ETA: 26s
 7782400/10531824 [=====================>........] - ETA: 26s
 7798784/10531824 [=====================>........] - ETA: 26s
 7815168/10531824 [=====================>........] - ETA: 25s
 7831552/10531824 [=====================>........] - ETA: 25s
 7847936/10531824 [=====================>........] - ETA: 25s
 7880704/10531824 [=====================>........] - ETA: 25s
 7913472/10531824 [=====================>........] - ETA: 24s
 7946240/10531824 [=====================>........] - ETA: 24s
 7962624/10531824 [=====================>........] - ETA: 24s
 7995392/10531824 [=====================>........] - ETA: 23s
 8011776/10531824 [=====================>........] - ETA: 23s
 8060928/10531824 [=====================>........] - ETA: 23s
 8093696/10531824 [======================>.......] - ETA: 22s
 8142848/10531824 [======================>.......] - ETA: 22s
 8175616/10531824 [======================>.......] - ETA: 21s
 8208384/10531824 [======================>.......] - ETA: 21s
 8257536/10531824 [======================>.......] - ETA: 20s
 8306688/10531824 [======================>.......] - ETA: 20s
 8339456/10531824 [======================>.......] - ETA: 19s
 8388608/10531824 [======================>.......] - ETA: 19s
 8404992/10531824 [======================>.......] - ETA: 19s
 8421376/10531824 [======================>.......] - ETA: 19s
 8437760/10531824 [=======================>......] - ETA: 18s
 8486912/10531824 [=======================>......] - ETA: 18s
 8503296/10531824 [=======================>......] - ETA: 18s
 8519680/10531824 [=======================>......] - ETA: 18s
 8536064/10531824 [=======================>......] - ETA: 17s
 8568832/10531824 [=======================>......] - ETA: 17s
 8601600/10531824 [=======================>......] - ETA: 17s
 8667136/10531824 [=======================>......] - ETA: 16s
 8683520/10531824 [=======================>......] - ETA: 16s
 8699904/10531824 [=======================>......] - ETA: 16s
 8749056/10531824 [=======================>......] - ETA: 15s
 8765440/10531824 [=======================>......] - ETA: 15s
 8814592/10531824 [========================>.....] - ETA: 15s
 8863744/10531824 [========================>.....] - ETA: 14s
 8896512/10531824 [========================>.....] - ETA: 14s
 8929280/10531824 [========================>.....] - ETA: 14s
 9019392/10531824 [========================>.....] - ETA: 13s
 9043968/10531824 [========================>.....] - ETA: 12s
 9076736/10531824 [========================>.....] - ETA: 12s
 9109504/10531824 [========================>.....] - ETA: 12s
 9175040/10531824 [=========================>....] - ETA: 11s
 9240576/10531824 [=========================>....] - ETA: 11s
 9289728/10531824 [=========================>....] - ETA: 10s
 9355264/10531824 [=========================>....] - ETA: 9s 
 9388032/10531824 [=========================>....] - ETA: 9s
 9420800/10531824 [=========================>....] - ETA: 9s
 9469952/10531824 [=========================>....] - ETA: 8s
 9502720/10531824 [==========================>...] - ETA: 8s
 9535488/10531824 [==========================>...] - ETA: 8s
 9568256/10531824 [==========================>...] - ETA: 7s
 9584640/10531824 [==========================>...] - ETA: 7s
 9633792/10531824 [==========================>...] - ETA: 7s
 9666560/10531824 [==========================>...] - ETA: 7s
 9715712/10531824 [==========================>...] - ETA: 6s
 9748480/10531824 [==========================>...] - ETA: 6s
 9781248/10531824 [==========================>...] - ETA: 6s
 9830400/10531824 [===========================>..] - ETA: 5s
 9879552/10531824 [===========================>..] - ETA: 5s
 9928704/10531824 [===========================>..] - ETA: 4s
 9977856/10531824 [===========================>..] - ETA: 4s
10043392/10531824 [===========================>..] - ETA: 3s
10059776/10531824 [===========================>..] - ETA: 3s
10141696/10531824 [===========================>..] - ETA: 3s
10158080/10531824 [===========================>..] - ETA: 2s
10190848/10531824 [============================>.] - ETA: 2s
10223616/10531824 [============================>.] - ETA: 2s
10256384/10531824 [============================>.] - ETA: 2s
10272768/10531824 [============================>.] - ETA: 2s
10305536/10531824 [============================>.] - ETA: 1s
10354688/10531824 [============================>.] - ETA: 1s
10387456/10531824 [============================>.] - ETA: 1s
10420224/10531824 [============================>.] - ETA: 0s
10436608/10531824 [============================>.] - ETA: 0s
10469376/10531824 [============================>.] - ETA: 0s
10534912/10531824 [==============================] - 81s 8us/step
Getting pre-trained model completed in 83.68 seconds
Failed to compute results: could not broadcast input array from shape (192,224,158) into shape (192,224,160)
Traceback (most recent call last):
  File "/Users/user/Downloads/Slicer-DeepSeg-main/Slicer-DeepSeg/DeepSeg/DeepSeg.py", line 638, in onApplyButton
    tumor_type = tumorType, output_shape = output_shape)
  File "/Users/user/Downloads/Slicer-DeepSeg-main/Slicer-DeepSeg/DeepSeg/DeepSegLib/predict.py", line 60, in predict_segmentations
    pred_data = postprocess_tumor(pred_data, tumor_type, output_shape)
  File "/Users/user/Downloads/Slicer-DeepSeg-main/Slicer-DeepSeg/DeepSeg/DeepSegLib/predict.py", line 45, in postprocess_tumor
    padded_seg[x:x+seg_data.shape[0],y:y+seg_data.shape[1],z:z+seg_data.shape[2]] = seg_data[:,:,2:padded_seg.shape[2]+2]
ValueError: could not broadcast input array from shape (192,224,158) into shape (192,224,160)`

**Comment by razeineldin** [comment]
Hello @matthieufaillot,

Thanks for your interest in our work and I am sorry for my late reply.

This error is related to the input MRI files you used. Please note that currently ONLY BraTS-compliant MRI cases can be processed using Slicer-DeepSeg (which has exactly an anisotropic resolution of 240 x 240 x 155).

Future work will include a generic pre-processing pipeline to support other MRI files as well.

Best,
Ramy
