### ISSUE TITLE
Failed to compute results: Incomplete or corrupted file detected. The sha256 file hash does not match the provided value of 941eb4b2c7da98310a95176e7adabe8f84d2e3df. 

### ISSUE THREAD

**Issue by platanus-study** [razeineldin/Slicer-DeepSeg#4]
Hello, I'm a person that is reproducting DeepSeg based on 3D-Slicer.

I'm running  DeepSeg module using  MICCAI_BraTS2020_TrainingData in 3D-Slicer as you inform in github.

I ran the DeepSeg module in 3D-Slicer as following.
1. Creation of DeepSeg module
1)I run 'Extension Wizard' module->2)Select 'Select Extension' button->3)Select 'Slicer-DeepSeg' folder-> 4)Select whether 'DeepSeg module' loads or not

2. I downloaded dataset
-MICCAI_BraTS2020_TrainingData

3. I run DeepSeg module using MICCAI_BraTS2020_TrainingData in 3D-Slicer 
    (1) After pressing 'Add Data' button in 'Welcome to Slicer' module, I imported 'BraTS20_Training_001' folder in MICCAI_BraTS2020_TrainingData.

    (2) And then I selected 'DeepSeg' module in 'modules finder' option.

    (3) In Inputs item, I selected 'BraTs20_Training_001_flair_1' in 'FLAIR Volume' option. 

    (4) In Outputs item, I selected one volume (MRI) dicom file in 'Tumor Volume'

    (5) I set the different options in  'Advanced Segmentation Parameters' item as following.:
       - Image Modalities : FLAIR
       - Corrped Image Shape :(192, 224, 160)
       - Tumor Type : Whole Tumor
       - 3D Background Colour : Black

 
After completing setting using DeepSeg module in 3D-Slicer, I pressed 'Apply' button.

But It occurs the error that is "Failed to compute results: Incomplete or corrupted file detected. The sha256 file hash does not match the provided value of 941eb4b2c7da98310a95176e7adabe8f84d2e3df.
Traceback (most recent call last):
  File "C:/Users/TRL 3D/Extension_dev/Slicer-DeepSeg/DeepSeg/DeepSeg.py", line 603, in onApplyButton modelPath = get_file(pretrainedURL.split("/")[-1], pretrainedURL, File "C:\Users\TRL 3D\AppData\Local\NA-MIC\Slicer 5.1.0-2022-07-01\lib\Python\Lib\site-packages\keras\utils\data_utils.py", line 298, in get_file
    raise ValueError(ValueError: Incomplete or corrupted file detected. The sha256 file hash does not match the provided value of 941eb4b2c7da98310a95176e7adabe8f84d2e3df.". 

Please, refer to attached image associated with error massage.
![sha256_error](https://user-images.githubusercontent.com/41041429/184850207-d1413721-fae4-47c9-ac00-888cb6541edb.png)

Please, let me know in detail how to solve this problem.

Thank you for reading my writing.

**Comment by razeineldin** [comment]
Hello @platanus-study,

Thanks for your interest in our work!

There was an error with the sha256sum hash value of DeepSeg pre-trained weights.
It is now fixed and you can try re-running the code again.

Best,
Ramy

**Comment by platanus-study** [comment]
Dear. @razeineldin 


I could run Slicer-DeepSeg well using example dataset without error thanks to you.

Thank you for modifying Slicer-DeepSeg code.
